//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avtaler
    {
        public System.Guid Id { get; set; }
        public string Avtalenummer { get; set; }
        public string Status { get; set; }
        public string KunderID { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
