//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kunder
    {
        public System.Guid Id { get; set; }
        public string BilensRegistreringsNummer { get; set; }
        public string PersonNummer { get; set; }
        public string ForNavn { get; set; }
        public string Etternavn { get; set; }
        public string Email { get; set; }
        public string Bonus { get; set; }
        public string KundeNummer { get; set; }
        public string AvtaleStatus { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
    }
}
